# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-15 22:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manual_tagging', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweettag',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
