# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-16 00:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manual_tagging', '0002_auto_20170415_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweettag',
            name='last_update',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='tweettag',
            name='tweet',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='manual_tagging.Tweet'),
        ),
        migrations.AlterField(
            model_name='tweettag',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
