# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-16 00:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manual_tagging', '0003_auto_20170415_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweettag',
            name='last_update',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
